### ISSUE TITLE
Filter for current academic year (term)

### ISSUE THREAD

**Issue by peternickson** [kingalfred/canvas-hod-reports#2]
All the courses in Canvas have terms assigned to them.  This information can be obtained from the courses api, but you have to specify that you want it:

> optional: the enrollment term object for the course returned only if
> include[]=term

I tested this out just now and it seems to work fine.  Here's the raw JSON from the Digital Leaders Group.  As you can see the term's name is Academic Year 2017-2018.  This is the term for all active courses.  By filtering for only the courses with this term, we can remove most of the "Courses with no assignments."

```

"id": 1137,
        "name": "Digital Leaders Group",
        "account_id": 2,
        "term": {
            "id": 38,
            "name": "Academic Year 2017-2018",
            "start_at": null,
            "end_at": "2018-07-30T23:00:00Z",
            "created_at": "2017-07-03T11:56:08Z",
            "workflow_state": "active",
            "grading_period_group_id": null,
            "sis_term_id": "2017start"
        },
```

**Comment by penguoir** [comment]
Fixed in https://github.com/kingalfred/canvas-hod-reports/commit/1f42076e4c92ec3b39c3326bd29a2dd8be74f7c8.
